# Airbnb in New York City - an explorative data analysis

On todays session we want to analyze the Airbnb offer in New York City using and improving our already learned knowledge about data science!

<img src="./img/NYC_2.jpg"> 

For this tutorial the following commands will be very helpful:

| commands | meaning |
| :-: | :-: |
| `pd.read_csv(<path>)` | Reading a .csv-File from your file System | 
| `len()` | return the length of an input object, for example the row count of an pandas dataframe | 
| `df.columns()` | returns the column names of a dataframe |
| `df.head(<n>)` | returns the first n rows of a dataframe | 
| `df.tail(<n>)` | returns the last n rows of a dataframe | 
| `df.loc[<index>]` | locator to filter a dataframe | 
| `df["<column_name>"]` | filter a dataframe to a given column / return only the specified column of a dataframe | 
| `df.sample(<n>)` | picks randomly n rows out of a dataframe | 
| `df.shape()` | returns the dimensions of a dataframe | 
| `df.unique()` | returns the unique values for each column of a dataframe |  
| `df.groupby("<column_name>")` | groups the information of a dataframe by the specified column | 
| `df.groupby("<column_name>").size()` | return the number of observation in each group | 
| `df.groupby("<column_name>").sort_values()` | sort the output by values, may based on a specified column | 
| `df.groupby("<column_name>").xs("<column_name>")` | extract a specific value set out of a grouped information which consists out of a multi level index | 
| `series.mean()` | calculates the mean value based on the given information list | 
| `df.describe()` | returns a statistical description for all columns of a given dataframe |

## Loading packages and dataset

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
airbnb_NY = pd.read_csv("../data/Airbnb_NYC.csv")

## Get to know the dataset

> **Question 1A)** How many observations are contained in the dataset?

> **Question 1B)** What columns are included in the dataset?

Okay, now let's get a quick overview:

> **Question 2A)** Show the first 10 observations of the dataset!

> **Question 2B)** Show the last 15 observations of the dataset!

> **Question 2C)** Choose randomly 15 observations out of the dataset and show them!

> **Question 2D)** Like C) but only the borough, property type and the price should be shown.

## The spatial context matters

Let's take a deeper look on the dataset

> **Question 3A)** Which boroughs of NYC are covered by the dataset?

> **Question 3B)** Which different kind of accomodations exists?

> **Question 3C)** How many airbnb offers exists per borough?

> **Question 3D)** Order the output from C) by the count of offers!

> **Question 3E)** Refine your search: How is the type of property influenced by the boroughs? Provide a table view!

> **Question 3F)** Provide a plot to visualize E) 
Try at first to provide a barplot only for Bronx and afterwards for all boroughs at the same time.

> **Question 3G)** Provide a plot to visualize the spatial distribution of the AirBnB´s.

> *Hint:* Remember the scatterplot function in matplotlib!

> **Question 3H)** Provide the same plot as in G) but for all individual boroughs!

## What about the prices?

> **Question 4A)** Which is the most expensive AirBnB?

> **Question 4B)** How many airbnb exists that are in price less than 50 $?

> **Question 4C)** Refining B) in which borough are most of them located?

> **Question 4D)** Take a closer look at C): Provide a ranking of the mean Review-count of these airbnbs per borough!

## Statistics count!

> **Question 5A**) What is the mean cost of an airbnb in NYC?

> **Question 5B)** How does the price vary?

> **Question 5C)** How is the price changing according to the property type? Which property type is the least expensive one?

> **Question 5D)** How does the mean airbnb price change according to the boroughs?

> **Question 5E)** Which are the top 10 rated airbnb per borough? Calculate the mean price of them!

In [17]:
airbnb_NY.groupby(['Boroughs'])[['Boroughs','Reviews30d']].apply(lambda x: x).sort_values(by='Reviews30d', ascending=False)

                  Boroughs  Reviews30d
Boroughs
Manhattan 25020  Manhattan       66.61
          24919  Manhattan       33.08
Queens    33920     Queens       20.49
          33955     Queens       19.19
          33958     Queens       17.31
...                    ...         ...
Manhattan 22264  Manhattan        0.01
          21944  Manhattan        0.01
Brooklyn  3801    Brooklyn        0.01
Manhattan 18549  Manhattan        0.01
          32821  Manhattan        0.01

[38733 rows x 2 columns]

In [6]:
airbnb_NY.columns

Index(['Boroughs', 'Latitude', 'Longitude', 'Prop_Type', 'Min_Nights',
       'Host_Listing_Cnt', 'Days_Available', 'Review_Cnt', 'Reviews30d',
       'Price'],
      dtype='object')

In [30]:
df_ratings = airbnb_NY.groupby(['Boroughs'])[['Boroughs','Reviews30d']].apply(lambda x: x)

In [34]:
df_ratings.loc[df_ratings['Boroughs']=='Bronx'].sort_values(by='Reviews30d', ascending=False)

             Boroughs  Reviews30d
Boroughs
Bronx    265    Bronx       10.41
         576    Bronx        9.62
         752    Bronx        9.00
         122    Bronx        8.44
         879    Bronx        8.31
...               ...         ...
         709    Bronx        0.03
         191    Bronx        0.02
         189    Bronx        0.02
         347    Bronx        0.02
         549    Bronx        0.02

[891 rows x 2 columns]